import streamlit as st 
import database.connection

st.header("Turmas por Escola")

# Consulta para obter todos os nomes das escolas
query_escolas = "SELECT NO_ENTIDADE FROM escola"
escolas_df = database.connection.run_query(query_escolas, True)

# Preencher o selectbox com os nomes das escolas
escolas_nomes = escolas_df["NO_ENTIDADE"].tolist()
escola_selecionada = st.selectbox("Selecione a escola:", escolas_nomes)

if escola_selecionada:
  query = f"""
    SELECT 
      t.NO_turma,
      CASE WHEN t.IN_DISC_QUIMICA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_QUIMICA,
      CASE WHEN t.IN_DISC_FISICA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_FISICA,
      CASE WHEN t.IN_DISC_MATEMATICA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_MATEMATICA,
      CASE WHEN t.IN_DISC_BIOLOGIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_BIOLOGIA,
      CASE WHEN t.IN_DISC_CIENCIAS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_CIENCIAS,
      CASE WHEN t.IN_DISC_LINGUA_PORTUGUESA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_PORTUGUESA,
      CASE WHEN t.IN_DISC_LINGUA_INGLES = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_INGLES,
      CASE WHEN t.IN_DISC_LINGUA_ESPANHOL = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_ESPANHOL,
      CASE WHEN t.IN_DISC_LINGUA_FRANCES = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_FRANCES,
      CASE WHEN t.IN_DISC_LINGUA_OUTRA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_OUTRA,
      CASE WHEN t.IN_DISC_LINGUA_INDIGENA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LINGUA_INDIGENA,
      CASE WHEN t.IN_DISC_ARTES = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_ARTES,
      CASE WHEN t.IN_DISC_EDUCACAO_FISICA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_EDUCACAO_FISICA,
      CASE WHEN t.IN_DISC_HISTORIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_HISTORIA,
      CASE WHEN t.IN_DISC_GEOGRAFIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_GEOGRAFIA,
      CASE WHEN t.IN_DISC_FILOSOFIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_FILOSOFIA,
      CASE WHEN t.IN_DISC_ENSINO_RELIGIOSO = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_ENSINO_RELIGIOSO,
      CASE WHEN t.IN_DISC_ESTUDOS_SOCIAIS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_ESTUDOS_SOCIAIS,
      CASE WHEN t.IN_DISC_SOCIOLOGIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_SOCIOLOGIA,
      CASE WHEN t.IN_DISC_EST_SOCIAIS_SOCIOLOGIA = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_EST_SOCIAIS_SOCIOLOGIA,
      CASE WHEN t.IN_DISC_INFORMATICA_COMPUTACAO = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_INFORMATICA_COMPUTACAO,
      CASE WHEN t.IN_DISC_PROFISSIONALIZANTE = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_PROFISSIONALIZANTE,
      CASE WHEN t.IN_DISC_ATENDIMENTO_ESPECIAIS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_ATENDIMENTO_ESPECIAIS,
      CASE WHEN t.IN_DISC_DIVER_SOCIO_CULTURAL = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_DIVER_SOCIO_CULTURAL,
      CASE WHEN t.IN_DISC_LIBRAS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_LIBRAS, 
      CASE WHEN t.IN_DISC_PEDAGOGICAS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_PEDAGOGICAS,
      CASE WHEN t.IN_DISC_OUTRAS = 1 THEN 'Sim' ELSE 'Não' END AS IN_DISC_OUTRAS
    FROM 
        turma t
    JOIN 
        escola e ON t.CO_ENTIDADE = e.CO_ENTIDADE
    WHERE 
      e.NO_ENTIDADE = '{escola_selecionada}';
  """

  turmas_df = database.connection.run_query(query, True)
  st.dataframe(turmas_df)